-- Migration: Initial Schema Creation
-- Purpose: Create core tables for Deal Intelligence + Property DD platform
-- Author: Generated by Claude
-- Date: 2026-09-04

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ============================================================================
-- USERS & AUTHENTICATION
-- ============================================================================

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    company_name VARCHAR(255),
    subscription_tier VARCHAR(50) DEFAULT 'trial', -- trial | deal_intel | property_dd | bundle
    subscription_status VARCHAR(50) DEFAULT 'active', -- active | trial | paused | cancelled
    stripe_customer_id VARCHAR(255) UNIQUE,
    trial_ends_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_stripe_customer_id ON users(stripe_customer_id);

-- ============================================================================
-- DEAL INTELLIGENCE DATA
-- ============================================================================

CREATE TABLE deals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    external_source_id VARCHAR(500),
    source VARCHAR(50) NOT NULL, -- crunchbase | preqin | news | pitchbook | linkedin
    deal_type VARCHAR(50), -- ma | pe | jv | fdi | other
    company_name VARCHAR(255) NOT NULL,
    industry VARCHAR(100),
    industry_tags TEXT[], -- Array for multiple tags
    deal_value_usd BIGINT,
    announced_date DATE,
    closed_date DATE,
    target_geography VARCHAR(2), -- ISO country code
    target_region VARCHAR(100), -- e.g., Southeast Asia, GCC
    acquiring_company VARCHAR(255),
    acquiring_geography VARCHAR(2),
    deal_description TEXT,
    deal_url VARCHAR(500),

    -- Scoring
    score INTEGER, -- 1-100
    score_breakdown JSONB, -- {sector: 20, geo: 30, size: 25, strategic: 25}
    scoring_methodology VARCHAR(100),
    scoring_version INTEGER DEFAULT 1,

    -- Raw data storage
    raw_data JSONB,

    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    indexed_at TIMESTAMP,

    UNIQUE(source, external_source_id)
);

CREATE INDEX idx_deals_announced_date ON deals(announced_date DESC);
CREATE INDEX idx_deals_score ON deals(score DESC);
CREATE INDEX idx_deals_target_geography ON deals(target_geography);
CREATE INDEX idx_deals_deal_type ON deals(deal_type);
CREATE INDEX idx_deals_source ON deals(source);
CREATE INDEX idx_deals_industry ON deals USING GIN(industry_tags);
CREATE INDEX idx_deals_created_at ON deals(created_at DESC);

-- ============================================================================
-- PROPERTY DATA
-- ============================================================================

CREATE TABLE properties (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    external_source_id VARCHAR(500),
    source VARCHAR(50), -- dubai_land_dept | thailand_dbd | sg_ura | etc
    property_type VARCHAR(50), -- residential | commercial | industrial | mixed
    address VARCHAR(500),
    city VARCHAR(100),
    country_code VARCHAR(2) NOT NULL,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),

    -- Property Details
    price_usd BIGINT,
    size_sqm DECIMAL(10, 2),
    year_built INTEGER,
    bedrooms INTEGER,
    bathrooms INTEGER,

    -- Legal Status
    ownership_legal_status VARCHAR(50), -- freehold | leasehold | restricted | mixed
    lease_remaining_years INTEGER,
    freehold_eligible BOOLEAN,
    foreign_ownership_allowed BOOLEAN,

    -- Due Diligence
    dd_status VARCHAR(50) DEFAULT 'pending', -- pending | in_progress | completed | flagged
    dd_data JSONB, -- {legal: {...}, tax: {...}, regulatory: {...}, risks: [...]}
    investment_score INTEGER, -- 1-100
    risk_level VARCHAR(20), -- low | medium | high
    acquisition_timeline_months INTEGER,

    -- Market Data
    market_comparable_price_usd BIGINT,
    appreciation_rate_annual DECIMAL(5, 2),
    rental_yield_annual DECIMAL(5, 2),

    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(source, external_source_id)
);

CREATE INDEX idx_properties_country_code ON properties(country_code);
CREATE INDEX idx_properties_property_type ON properties(property_type);
CREATE INDEX idx_properties_investment_score ON properties(investment_score DESC);
CREATE INDEX idx_properties_dd_status ON properties(dd_status);
CREATE INDEX idx_properties_risk_level ON properties(risk_level);
CREATE INDEX idx_properties_location ON properties USING GIST(ll_to_earth(latitude, longitude));

-- ============================================================================
-- USER ALERTS & SUBSCRIPTIONS
-- ============================================================================

CREATE TABLE user_alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    alert_type VARCHAR(50), -- deal | property | both
    alert_name VARCHAR(255),

    -- Criteria (JSON for flexibility)
    criteria JSONB, -- {sectors: [...], geographies: [...], value_min: ..., value_max: ...}

    -- Settings
    frequency VARCHAR(50) DEFAULT 'realtime', -- realtime | daily | weekly
    enabled BOOLEAN DEFAULT true,
    last_triggered_at TIMESTAMP,
    trigger_count INTEGER DEFAULT 0,

    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_alerts_user_id ON user_alerts(user_id);
CREATE INDEX idx_user_alerts_enabled ON user_alerts(enabled);
CREATE INDEX idx_user_alerts_user_enabled ON user_alerts(user_id, enabled);

-- ============================================================================
-- ALERT HISTORY (for user dashboard)
-- ============================================================================

CREATE TABLE alert_triggers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    alert_id UUID NOT NULL REFERENCES user_alerts(id) ON DELETE CASCADE,
    deal_id UUID REFERENCES deals(id) ON DELETE SET NULL,
    property_id UUID REFERENCES properties(id) ON DELETE SET NULL,

    -- Alert details
    alert_message TEXT,
    match_score DECIMAL(5, 2), -- How well it matched (0-1)
    was_read BOOLEAN DEFAULT false,
    read_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_alert_triggers_alert_id ON alert_triggers(alert_id);
CREATE INDEX idx_alert_triggers_created_at ON alert_triggers(created_at DESC);
CREATE INDEX idx_alert_triggers_was_read ON alert_triggers(was_read);

-- ============================================================================
-- SCORING HISTORY (for A/B testing & debugging)
-- ============================================================================

CREATE TABLE scoring_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    deal_id UUID REFERENCES deals(id) ON DELETE CASCADE,
    property_id UUID REFERENCES properties(id) ON DELETE CASCADE,

    scoring_version INTEGER,
    score_value INTEGER,
    score_breakdown JSONB,
    methodology VARCHAR(100),
    model_version VARCHAR(50), -- e.g., claude-3.5-sonnet-v1

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scoring_history_deal_id ON scoring_history(deal_id);
CREATE INDEX idx_scoring_history_property_id ON scoring_history(property_id);

-- ============================================================================
-- SUBSCRIPTION & PAYMENT
-- ============================================================================

CREATE TABLE subscriptions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,

    tier VARCHAR(50), -- deal_intel | property_dd | bundle
    status VARCHAR(50), -- active | paused | cancelled

    stripe_subscription_id VARCHAR(255) UNIQUE,
    stripe_price_id VARCHAR(255),
    current_period_start DATE,
    current_period_end DATE,

    cancel_at_period_end BOOLEAN DEFAULT false,
    cancelled_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_subscriptions_user_id ON subscriptions(user_id);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);

-- ============================================================================
-- API USAGE TRACKING (for rate limiting & analytics)
-- ============================================================================

CREATE TABLE api_usage (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    endpoint VARCHAR(255),
    method VARCHAR(10),
    status_code INTEGER,
    response_time_ms INTEGER,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_api_usage_user_id ON api_usage(user_id);
CREATE INDEX idx_api_usage_created_at ON api_usage(created_at);

-- ============================================================================
-- AUDIT LOG (for security & compliance)
-- ============================================================================

CREATE TABLE audit_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,

    action VARCHAR(100),
    resource_type VARCHAR(50),
    resource_id VARCHAR(255),
    details JSONB,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_log_user_id ON audit_log(user_id);
CREATE INDEX idx_audit_log_created_at ON audit_log(created_at);

-- ============================================================================
-- TRIGGERS FOR UPDATED_AT
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_deals_updated_at BEFORE UPDATE ON deals
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_properties_updated_at BEFORE UPDATE ON properties
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_alerts_updated_at BEFORE UPDATE ON user_alerts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_subscriptions_updated_at BEFORE UPDATE ON subscriptions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
